<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="140942" started-at="2020-02-27T08:52:28Z" finished-at="2020-02-27T08:54:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="140942" started-at="2020-02-27T08:52:28Z" finished-at="2020-02-27T08:54:49Z">
      <class name="Cases.CaseOne">
        <test-method status="PASS" signature="ExtentSet()[pri:0, instance:Cases.CaseOne@7085bdee]" name="ExtentSet" is-config="true" duration-ms="731" started-at="2020-02-27T08:52:27Z" finished-at="2020-02-27T08:52:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtentSet -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseOne@7085bdee]" name="init" is-config="true" duration-ms="12724" started-at="2020-02-27T08:54:03Z" finished-at="2020-02-27T08:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="caseOne()[pri:0, instance:Cases.CaseOne@7085bdee]" name="caseOne" duration-ms="5" started-at="2020-02-27T08:54:15Z" finished-at="2020-02-27T08:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseOne -->
        <test-method status="PASS" signature="tearDowntest()[pri:0, instance:Cases.CaseOne@7085bdee]" name="tearDowntest" is-config="true" duration-ms="5291" started-at="2020-02-27T08:54:15Z" finished-at="2020-02-27T08:54:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDowntest -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseOne@7085bdee]" name="init" is-config="true" duration-ms="12159" started-at="2020-02-27T08:54:21Z" finished-at="2020-02-27T08:54:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="clickNewEvent()[pri:0, instance:Cases.CaseOne@7085bdee]" name="clickNewEvent" duration-ms="10678" started-at="2020-02-27T08:54:33Z" finished-at="2020-02-27T08:54:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickNewEvent -->
        <test-method status="PASS" signature="tearDowntest()[pri:0, instance:Cases.CaseOne@7085bdee]" name="tearDowntest" is-config="true" duration-ms="5463" started-at="2020-02-27T08:54:44Z" finished-at="2020-02-27T08:54:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDowntest -->
      </class> <!-- Cases.CaseOne -->
      <class name="Cases.CaseTwo">
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="15910" started-at="2020-02-27T08:52:28Z" finished-at="2020-02-27T08:52:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="caseEight()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseEight" duration-ms="46" started-at="2020-02-27T08:52:44Z" finished-at="2020-02-27T08:52:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Cases.CaseTwo.caseEight(CaseTwo.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseEight -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1681" started-at="2020-02-27T08:52:46Z" finished-at="2020-02-27T08:52:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="13084" started-at="2020-02-27T08:52:48Z" finished-at="2020-02-27T08:53:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="caseEight()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseEight" duration-ms="5" started-at="2020-02-27T08:53:01Z" finished-at="2020-02-27T08:53:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Cases.CaseTwo.caseEight(CaseTwo.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseEight -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1421" started-at="2020-02-27T08:53:02Z" finished-at="2020-02-27T08:53:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="12916" started-at="2020-02-27T08:53:04Z" finished-at="2020-02-27T08:53:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="caseEight()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseEight" duration-ms="4" started-at="2020-02-27T08:53:17Z" finished-at="2020-02-27T08:53:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Cases.CaseTwo.caseEight(CaseTwo.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseEight -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1384" started-at="2020-02-27T08:53:18Z" finished-at="2020-02-27T08:53:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="12414" started-at="2020-02-27T08:53:20Z" finished-at="2020-02-27T08:53:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="caseFive()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseFive" duration-ms="3" started-at="2020-02-27T08:53:32Z" finished-at="2020-02-27T08:53:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseFive -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1419" started-at="2020-02-27T08:53:32Z" finished-at="2020-02-27T08:53:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="12330" started-at="2020-02-27T08:53:34Z" finished-at="2020-02-27T08:53:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="caseSeven()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseSeven" duration-ms="3" started-at="2020-02-27T08:53:46Z" finished-at="2020-02-27T08:53:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseSeven -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1363" started-at="2020-02-27T08:53:46Z" finished-at="2020-02-27T08:53:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="init()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="init" is-config="true" duration-ms="12367" started-at="2020-02-27T08:53:47Z" finished-at="2020-02-27T08:54:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="caseSix()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="caseSix" duration-ms="3" started-at="2020-02-27T08:54:00Z" finished-at="2020-02-27T08:54:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Cases.CaseTwo.caseSix(CaseTwo.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- caseSix -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Cases.CaseTwo@1ce92674]" name="tearDown" is-config="true" duration-ms="1267" started-at="2020-02-27T08:54:01Z" finished-at="2020-02-27T08:54:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Cases.CaseTwo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
